#!/bin/bash
# Generate a starter design token CSS file (blue brand palette)
# Outputs a complete 3-tier token template to stdout
# Customize the color values after generation to match your brand
# Usage: generate-tokens.sh > tokens.css

cat << 'TOKENS'
/* ============================================
   Design Tokens — Generated by design-studio
   ============================================ */

/* ===================
   TIER 1: PRIMITIVES
   =================== */

:root {
  /* Color Primitives — Brand */
  --color-brand-50: #eff6ff;
  --color-brand-100: #dbeafe;
  --color-brand-200: #bfdbfe;
  --color-brand-300: #93c5fd;
  --color-brand-400: #60a5fa;
  --color-brand-500: #3b82f6;
  --color-brand-600: #2563eb;
  --color-brand-700: #1d4ed8;
  --color-brand-800: #1e40af;
  --color-brand-900: #1e3a8a;

  /* Color Primitives — Neutral */
  --color-gray-50: #f9fafb;
  --color-gray-100: #f3f4f6;
  --color-gray-200: #e5e7eb;
  --color-gray-300: #d1d5db;
  --color-gray-400: #9ca3af;
  --color-gray-500: #6b7280;
  --color-gray-600: #4b5563;
  --color-gray-700: #374151;
  --color-gray-800: #1f2937;
  --color-gray-900: #111827;
  --color-gray-950: #030712;

  /* Color Primitives — Status */
  --color-green-500: #22c55e;
  --color-green-600: #16a34a;
  --color-green-50: #f0fdf4;
  --color-amber-500: #f59e0b;
  --color-amber-600: #d97706;
  --color-amber-50: #fffbeb;
  --color-red-500: #ef4444;
  --color-red-600: #dc2626;
  --color-red-50: #fef2f2;
  --color-blue-500: #3b82f6;
  --color-blue-50: #eff6ff;

  /* Spacing Primitives (4px base) */
  --space-0: 0;
  --space-1: 0.25rem;   /* 4px */
  --space-2: 0.5rem;    /* 8px */
  --space-3: 0.75rem;   /* 12px */
  --space-4: 1rem;      /* 16px */
  --space-5: 1.25rem;   /* 20px */
  --space-6: 1.5rem;    /* 24px */
  --space-8: 2rem;      /* 32px */
  --space-10: 2.5rem;   /* 40px */
  --space-12: 3rem;     /* 48px */
  --space-16: 4rem;     /* 64px */
  --space-20: 5rem;     /* 80px */
  --space-24: 6rem;     /* 96px */

  /* Typography Primitives (1.25 ratio) */
  --text-xs: 0.75rem;    /* 12px */
  --text-sm: 0.875rem;   /* 14px */
  --text-base: 1rem;     /* 16px */
  --text-lg: 1.125rem;   /* 18px */
  --text-xl: 1.25rem;    /* 20px */
  --text-2xl: 1.5rem;    /* 24px */
  --text-3xl: 1.875rem;  /* 30px */
  --text-4xl: 2.25rem;   /* 36px */
  --text-5xl: 3rem;      /* 48px */

  /* Radius Primitives */
  --radius-sm: 0.25rem;   /* 4px */
  --radius-md: 0.375rem;  /* 6px */
  --radius-lg: 0.5rem;    /* 8px */
  --radius-xl: 0.75rem;   /* 12px */
  --radius-2xl: 1rem;     /* 16px */
  --radius-full: 9999px;

  /* Shadow Primitives */
  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);
  --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
  --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  --shadow-xl: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);

  /* ====================
     TIER 2: SEMANTIC
     ==================== */

  /* Surface */
  --surface-primary: var(--color-gray-50);
  --surface-secondary: white;
  --surface-elevated: white;
  --surface-overlay: rgb(0 0 0 / 0.5);

  /* Text */
  --text-primary: var(--color-gray-900);
  --text-secondary: var(--color-gray-600);
  --text-tertiary: var(--color-gray-400);
  --text-inverse: white;
  --text-link: var(--color-brand-600);

  /* Border */
  --border-default: var(--color-gray-200);
  --border-strong: var(--color-gray-300);
  --border-focus: var(--color-brand-500);

  /* Interactive */
  --interactive-primary: var(--color-brand-600);
  --interactive-primary-hover: var(--color-brand-700);
  --interactive-secondary: var(--color-gray-100);
  --interactive-secondary-hover: var(--color-gray-200);

  /* Status */
  --status-success: var(--color-green-600);
  --status-success-bg: var(--color-green-50);
  --status-warning: var(--color-amber-600);
  --status-warning-bg: var(--color-amber-50);
  --status-error: var(--color-red-600);
  --status-error-bg: var(--color-red-50);
  --status-info: var(--color-blue-500);
  --status-info-bg: var(--color-blue-50);

  /* ====================
     TIER 3: COMPONENT
     ==================== */

  /* Button */
  --btn-primary-bg: var(--interactive-primary);
  --btn-primary-text: var(--text-inverse);
  --btn-primary-hover: var(--interactive-primary-hover);
  --btn-secondary-bg: transparent;
  --btn-secondary-border: var(--border-default);
  --btn-secondary-text: var(--text-primary);
  --btn-padding-x: var(--space-4);
  --btn-padding-y: var(--space-2);
  --btn-radius: var(--radius-lg);

  /* Card */
  --card-bg: var(--surface-secondary);
  --card-border: var(--border-default);
  --card-radius: var(--radius-xl);
  --card-shadow: var(--shadow-sm);
  --card-padding: var(--space-6);

  /* Input */
  --input-bg: var(--surface-secondary);
  --input-border: var(--border-default);
  --input-border-focus: var(--border-focus);
  --input-radius: var(--radius-lg);
  --input-padding-x: var(--space-3);
  --input-padding-y: var(--space-2);
  --input-error-border: var(--status-error);
}

/* ====================
   DARK MODE
   ==================== */

@media (prefers-color-scheme: dark) {
  :root {
    --surface-primary: var(--color-gray-950);
    --surface-secondary: var(--color-gray-900);
    --surface-elevated: var(--color-gray-800);

    --text-primary: var(--color-gray-50);
    --text-secondary: var(--color-gray-400);
    --text-tertiary: var(--color-gray-500);

    --border-default: var(--color-gray-700);
    --border-strong: var(--color-gray-600);

    --interactive-secondary: var(--color-gray-800);
    --interactive-secondary-hover: var(--color-gray-700);

    --card-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.3);
  }
}
TOKENS
